# Generated by Django 5.2.4 on 2025-08-01 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatsession',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
