# Generated by Django 5.2.4 on 2025-08-01 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_chatsession_id_alter_message_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sucursal', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.CreateModel(
            name='UsuarioMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asociacion', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.message')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.usuario')),
            ],
        ),
    ]
