# Generated by Django 5.2.4 on 2025-08-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_usuario_remove_message_chat_usuariomensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='categorie',
            field=models.CharField(choices=[('MA', 'Marcajes'), ('AC', 'Acceso de Cuenta'), ('RL', 'Reduccion Laboral'), ('CM', 'Cargue de Mallas'), ('MP', 'Movimiento de Personal'), ('OR', 'Otro')], default='OR', max_length=2),
        ),
    ]
